#!/bin/bash
curl https://sh.rustup.rs -sSf | sh -s -- -y
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc

$HOME/.cargo/bin/rustup component add rust-src
$HOME/.cargo/bin/cargo install evcxr_jupyter
#evcxr_jupyter --install
